import { StyleSheet } from "react-native";

const MAROON = "#95223D";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  header: {
    paddingTop: 48,
    paddingHorizontal: 20,
    paddingBottom: 12,
    backgroundColor: "#fff",
  },
  title: { fontSize: 26, fontWeight: "700", color: MAROON },
  subtitle: { marginTop: 4, fontSize: 15, color: "#666" },
  currentBuildingText: { marginTop: 6, fontSize: 13, color: "#2563eb" },
  buildingLabel: {
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(149, 34, 61, 0.35)",
  },
  buildingLabelText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#95223D",
  },
  campusLabel: {
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(149, 34, 61, 0.35)",
  },
  campusLabelText: {
    fontSize: 13,
    fontWeight: "900",
    color: MAROON,
  },

  map: { flex: 1 },

  loadingContainer: { flex: 1, alignItems: "center", justifyContent: "center" },
  loadingText: { color: "#666" },

  indoorHandoffWrap: {
    position: "absolute",
    top: 146,
    left: 16,
    right: 16,
    zIndex: 49,
    alignItems: "center",
  },
  indoorHandoffButton: {
    minWidth: 180,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  indoorHandoffButtonText: {
    color: MAROON,
    fontSize: 13,
    fontWeight: "800",
  },
  poiButton: {
    position: "absolute",
    right: 16,
    bottom: 380,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 35,
    elevation: 12,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    overflow: "hidden",
  },
  /** Sit above the filter form panel (poiPanel at bottom: 120, ~300px+ tall) */
  poiButtonClearFilterPanel: {
    bottom: 505,
  },
  poiButtonActive: {
    borderWidth: 2,
    borderColor: MAROON,
  },
  poiButtonIcon: {
    color: MAROON,
  },
  poiPanel: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 120,
    backgroundColor: "#F7F4EF",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    zIndex: 25,
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  poiPanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  poiPanelTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1F1F1F",
  },
  poiPanelSectionLabel: {
    color: MAROON,
    fontSize: 14,
    marginBottom: 8,
  },
  poiCategoryRow: {
    flexDirection: "row",
    marginBottom: 12,
  },
  poiCategoryChip: {
    backgroundColor: "#E6E1D8",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    marginRight: 8,
  },
  poiCategoryChipActive: {
    backgroundColor: MAROON,
  },
  poiCategoryChipText: {
    color: "#1F1F1F",
    fontWeight: "600",
  },
  poiCategoryChipTextActive: {
    color: "#FFF",
  },
  poiRadiusRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  poiRadiusButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#E6E1D8",
    alignItems: "center",
    justifyContent: "center",
  },
  poiRadiusButtonText: {
    fontSize: 18,
    color: MAROON,
    fontWeight: "700",
  },
  poiRadiusValueBox: {
    minWidth: 74,
    marginHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#DDD6CA",
  },
  poiRadiusValueText: {
    fontWeight: "600",
    color: "#1F1F1F",
  },
  poiStatusText: {
    color: "#666",
    marginBottom: 8,
  },
  poiResultRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E0D7",
  },
  poiResultTitle: {
    fontWeight: "700",
    color: "#1F1F1F",
  },
  poiResultAddress: {
    color: "#666",
    fontSize: 12,
    marginTop: 2,
  },
  poiInfoCardContainer: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 22,
  },
  poiInfoCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  poiInfoTitle: { fontSize: 16, fontWeight: "800", color: "#111", flex: 1 },
  poiInfoTag: {
    backgroundColor: MAROON,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  poiInfoTagText: { color: "#fff", fontWeight: "800", fontSize: 12 },
  poiInfoDistance: {
    marginLeft: 12,
    fontSize: 12,
    fontWeight: "700",
    color: "#222",
  },
  poiInfoAddress: { marginTop: 12, fontSize: 13, color: "#333", lineHeight: 18 },
  poiInfoCTA: {
    marginTop: 16,
    backgroundColor: MAROON,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  poiInfoCTAText: { color: "#fff", fontWeight: "800", fontSize: 15 },
  poiMarker: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: MAROON,
    borderWidth: 2,
    borderColor: "#FFF",
  },
  recenterBtn: {
    position: "absolute",
    left: 16,
    bottom: 80,
    backgroundColor: "#fff",
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 30,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111",
  },
  modalClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F2F2F2",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseText: { fontSize: 16, color: "#333", fontWeight: "700" },
  modalSubtitle: {
    marginTop: 10,
    fontSize: 13,
    fontWeight: "700",
    color: "#111",
  },
  modalAddress: {
    marginTop: 2,
    fontSize: 12,
    color: "#666",
  },
  modalSchedule: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#F7F7F7",
  },
  modalSection: {
    marginTop: 12,
  },
  modalScheduleTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#111",
  },
  modalScheduleText: {
    marginTop: 4,
    fontSize: 12,
    color: "#444",
  },
  modalDepartures: {
    marginTop: 12,
  },
  modalEmpty: {
    marginTop: 6,
    fontSize: 12,
    color: "#666",
  },
  departureRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  departureIcon: { width: 20, height: 20 },
  departureTime: {
    width: 56,
    fontSize: 14,
    fontWeight: "700",
    color: "#111",
    fontVariant: ["tabular-nums"],
  },
  departureEta: {
    marginLeft: "auto",
    width: 70,
    fontSize: 12,
    color: "#666",
    fontWeight: "600",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
});

export default styles;
