import { StyleSheet } from "react-native";

const MAROON = "#95223D";

const styles = StyleSheet.create({

  container: { flex: 1, backgroundColor: "#fff" },
  header: {
    paddingTop: 48,
    paddingHorizontal: 20,
    paddingBottom: 12,
    backgroundColor: "#fff",
  },
  title: { fontSize: 26, fontWeight: "700", color: MAROON },
  subtitle: { marginTop: 4, fontSize: 15, color: "#666" },
  currentBuildingText: { marginTop: 6, fontSize: 13, color: "#2563eb" },
  buildingLabel: {
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(149, 34, 61, 0.35)",
  },
  buildingLabelText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#95223D",
  },
  campusLabel: {
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(149, 34, 61, 0.35)",
  },
  campusLabelText: {
    fontSize: 13,
    fontWeight: "900",
    color: MAROON,
  },

  map: { flex: 1 },

  loadingContainer: { flex: 1, alignItems: "center", justifyContent: "center" },
  loadingText: { color: "#666" },

  redBox: {
    position: "absolute",
    top: 10,
    left: 16,
    right: 16,
    zIndex: 50,
    backgroundColor: MAROON,
    borderRadius: 22,
    padding: 12,
  },
  inputRow: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
  },

  input: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    paddingVertical: 0,
    flex: 1,
  },
  searchIcon: {
    width: 16,
    height: 16,
    marginRight: 8,
    opacity: 0.8,
  },
  inputPlaceholder: {
    fontSize: 12,
    fontStyle: "italic",
    fontWeight: "500",
  },
  searchResults: {
    marginTop: 8,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 12,
    overflow: "hidden",
  },
  searchResultRow: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.12)",
  },
  searchResultText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  clearBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  clearBtnText: { color: "#fff", fontSize: 12, fontWeight: "800" },
  swapBtn: {
    position: "absolute",
    right: 350,
    top: 47,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },

  sheetWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  sheet: {
    backgroundColor: "#fff",
    borderRadius: 22,
    paddingTop: 10,
    paddingHorizontal: 16,
    paddingBottom: 18,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#E6E6E6",
    marginBottom: 12,
  },
  sheetHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  sheetHeaderLeft: { flexDirection: "row", gap: 12, flex: 1, paddingRight: 8 },

  buildingIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: MAROON,
    alignItems: "center",
    justifyContent: "center",
  },
  buildingIconImage: { width: 28, height: 28 },
  buildingTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
    letterSpacing: 0.4,
  },
  buildingSub: { marginTop: 4, fontSize: 13, color: "#666", lineHeight: 18 },

  amenitiesWrap: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#EAEAEA",
  },
  amenitiesTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#111",
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  amenityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  amenityLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    paddingRight: 10,
  },
  amenityLabel: {
    fontSize: 13,
    color: "#333",
    fontWeight: "700",
    flexShrink: 1,
  },
  amenityValue: {
    fontSize: 13,
    color: "#666",
    fontWeight: "800",
  },

  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#F2F2F2",
    alignItems: "center",
    justifyContent: "center",
  },
  closeBtnText: { fontSize: 16, color: "#333", fontWeight: "700" },

  directionsBtn: {
    marginTop: 16,
    backgroundColor: MAROON,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  directionsBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  directionsBtnIcon: { width: 18, height: 18 },
  directionsWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  recenterBtn: {
    position: "absolute",
    left: 16,
    bottom: 80,
    backgroundColor: "#fff",
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  directionsPanel: {
    backgroundColor: "#fff",
    borderRadius: 22,
    paddingVertical: 14,
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  modeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  modeBtn: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E6E6E6",
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  modeBtnActive: {
    borderColor: MAROON,
    backgroundColor: "rgba(149, 34, 61, 0.08)",
  },
  modeBtnLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#444",
  },
  modeBtnTextActive: {
    color: MAROON,
  },
  shuttlePanel: {
    marginTop: 8,
    marginBottom: 6,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "#F7F7F7",
  },
  transitSubRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  transitSubBtn: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    paddingVertical: 8,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  transitSubBtnActive: {
    borderColor: MAROON,
    backgroundColor: "rgba(149, 34, 61, 0.08)",
  },
  transitSubText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#444",
  },
  transitSubTextActive: {
    color: MAROON,
  },
  shuttleBtn: {
    backgroundColor: MAROON,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  shuttleBtnText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
  },
  shuttleNote: {
    marginTop: 6,
    fontSize: 11,
    color: "#666",
    textAlign: "center",
  },
  transitList: {
    marginTop: 8,
    gap: 8,
  },
  transitSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  transitSummaryLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
  },
  transitBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 10,
    backgroundColor: "#F3F3F3",
  },
  transitBadgeText: {
    fontSize: 11,
    color: "#111",
    fontWeight: "700",
  },
  transitMeta: {
    fontSize: 11,
    color: "#555",
    fontWeight: "700",
  },
  transitHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  collapseBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(149, 34, 61, 0.08)",
  },
  transitRow: {
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EDEDED",
  },
  transitRowActive: {
    borderColor: MAROON,
    backgroundColor: "rgba(149, 34, 61, 0.06)",
  },
  transitLine: {
    fontSize: 12,
    fontWeight: "800",
    color: "#111",
  },
  transitLineActive: {
    color: MAROON,
  },
  transitStops: {
    marginTop: 2,
    fontSize: 11,
    color: "#444",
  },
  transitTimes: {
    marginTop: 2,
    fontSize: 11,
    color: "#666",
  },
  transitEmpty: {
    fontSize: 11,
    color: "#666",
    textAlign: "center",
    paddingVertical: 6,
  },
  transitSteps: {
    marginTop: 6,
    gap: 4,
  },
  transitStepRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  transitStepText: {
    fontSize: 11,
    color: "#333",
    flex: 1,
  },
  transitStopCount: {
    fontSize: 11,
    color: "#666",
    fontWeight: "600",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 30,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111",
  },
  modalClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F2F2F2",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseText: { fontSize: 16, color: "#333", fontWeight: "700" },
  modalSubtitle: {
    marginTop: 10,
    fontSize: 13,
    fontWeight: "700",
    color: "#111",
  },
  modalAddress: {
    marginTop: 2,
    fontSize: 12,
    color: "#666",
  },
  modalSchedule: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#F7F7F7",
  },
  modalSection: {
    marginTop: 12,
  },
  modalScheduleTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#111",
  },
  modalScheduleText: {
    marginTop: 4,
    fontSize: 12,
    color: "#444",
  },
  modalDepartures: {
    marginTop: 12,
  },
  modalEmpty: {
    marginTop: 6,
    fontSize: 12,
    color: "#666",
  },
  departureRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  departureIcon: { width: 20, height: 20 },
  departureTime: {
    width: 56,
    fontSize: 14,
    fontWeight: "700",
    color: "#111",
    fontVariant: ["tabular-nums"],
  },
  departureEta: {
    marginLeft: "auto",
    width: 70,
    fontSize: 12,
    color: "#666",
    fontWeight: "600",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  routeInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  routeInfoActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  routeInfoTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
  },
  routeInfoSub: {
    marginTop: 2,
    fontSize: 12,
    color: "#666",
  },
  goBtn: {
    backgroundColor: MAROON,
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 22,
  },
  goBtnText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  simBtn: {
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#E6E6E6",
    backgroundColor: "#fff",
  },
  simBtnActive: {
    borderColor: MAROON,
    backgroundColor: "rgba(149, 34, 61, 0.08)",
  },
  simBtnText: {
    color: "#444",
    fontSize: 12,
    fontWeight: "700",
  },
  simBtnTextActive: {
    color: MAROON,
  },
  muteBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E6E6E6",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  muteBtnActive: {
    borderColor: MAROON,
    backgroundColor: "rgba(149, 34, 61, 0.08)",
  },
});

export default styles;
